import Head from 'next/head'
import Navbar from '../components/navbar'
import Test from '../components/test'
import Home from './Home'
import Footer from '../components/footer'


export default function App() {
  return (
    <div>
      <Head>
        <title>GameRumble</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.13.1/css/all.css"
          integrity="sha384-xxzQGERXS00kBmZW/6qxqJPyxW3UR0BPsL4c8ILaIWXva5kFi7TxkIIaMiKtqV1Q"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=PT+Sans:wght@700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Navbar />
      <Home/>
      <Footer />
    </div>
  )
}
